sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
      
install:
  - npm install haxeshim -g
  - npm install lix -g
  - lix download
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix node
